FROM ubuntu:latest as builder

RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install --break-system-packages xpip.build

WORKDIR /app

COPY . .
RUN pip3 install --break-system-packages -r requirements.txt
RUN xpip-build --debug setup --all

FROM python:3.9-slim as runner

WORKDIR /app

COPY --from=builder /app/dist/*.whl .

RUN pip install --no-cache-dir *.whl

EXPOSE 3000

CMD ["xpw-locker", "--stdout", "--debug"]
